### ISSUE TITLE
crash with bidoof 1.3.1 (Fix so I have bidoof)

### ISSUE THREAD

**Issue by arandommenno** [RacoonDog/bidoof-meteor#5]
When I start the client with the the mods listed in the crash report the game crashes.
And I am no crash report person but I have not enough crashes and it says that bidoof is the problem.
[crash-2022-10-31_14.54.24-client.txt](https://github.com/RacoonDog/bidoof-meteor/files/9901709/crash-2022-10-31_14.54.24-client.txt)

**Comment by crosby-moe** [comment]
yeah i know
if its urgent you can probably just use a later version of MSAU

**Comment by crosby-moe** [comment]
pretty sure i fixed it 👍 
try redownloading it and see if it works

**Comment by arandommenno** [comment]
Okay I'll test as soon as I have time.

**Comment by arandommenno** [comment]
It is fixed Thank you very much.
